### DISCUSSION TITLE
Random variables in configs

### DISCUSSION THREAD

**Discussion by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai-unity#3] [Ideas]
It would great to be able to randomise configurations but have the relative positions of objects remain fixed. I am imagining a config like this:

```
!ArenaConfig

random_var: "random" #define a random variable (which has to be less than 40 at least)

arenas:
  0: !Arena
    pass_mark: 0
    t: 1000
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x:  20, y: 0, z: "random"}
      rotations: [0]
    - !Item
       name: GoodGoal
       positions:
       - !Vector3 {x: 20, y: 0, z: "random" + 5}
       rotations: [0]

```

Here, the agent and the goal are both spawned in the middle of the arena on the x-axis and then at "random"'s value on the z, but always 5 units apart. I realise it would be hard if "random" gets initialised to 38 or something, then the goodgoal would spawn out of the arena, but something along these lines would be cool.
