### DISCUSSION TITLE
Toggle Arena Size and Aesthetics

### DISCUSSION THREAD

**Discussion by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai-unity#8] [Ideas]
At the moment the arena is fixed to be 40x40x40 with a picket fence and a tiled floor. It would be great if we could add parameters to the arena object, along with `t` and `pass_mark` that allow us to define the size of the arena and to use a mixture of textures and RGB values for the walls and floor (perhaps also the ceiling). I'm thinking something along the lines of:

```
!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 1000
    arena_size: !Vector3 {x: 40, y: 40, z: 40} # changeable between some range {1,1,1} to, say, {100,100,100} or even, open-ended? (But then difficult to define coordinates of alter objects)
    floor_color: "tiled", "stripy", "whitenoise", !RGB {r: 10, g: 153, b: 255}
    wall_color: "picket", "forest-scene", "whitenoise", !RGB {r: 10, g: 153, b: 255} # perhaps even a different parameter for each wall?
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]

```
