### ISSUE TITLE
Error in arena cycling in play mode

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai-unity#33]
When playing the following config with multiple arenas, I occasionally get an error where the arena skips to the next one several times in quick succession, until settling on one of the arenas. Each arena works individually, and the skipping doesn't seem to be dependent on the particular arena.

1. Run the following config in play mode using a jupyter notebook, the latest AAI release and the latest PyPI release.
```YAML
!ArenaConfig
showNotification: true
arenas:
  0: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
  1: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
  2: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
    - !Item
      name: BadGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
  3: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 10, y: 2, z: 2}
      rotations: [0]
```

**Expected behavior**
Arenas should cycle through and enable the player to play each episode unless they skip it.

**Screenshots**
Contact me for a screen capture of the problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
